### ISSUE TITLE
Can't find file: local.settings.json in the root of the Sketch2Code.Api project.

### ISSUE THREAD

**Issue by quan7794** [Microsoft/AISchoolTutorials#6]
As title, your tutorial have some step to modifiy local.settings.json file. But I can't see any file like that. Please upload this file. Thanks so much.

**Comment by gsegares** [comment]
Duplicated with [Issue #4](https://github.com/Microsoft/AISchoolTutorials/issues/4), I'll close this one.

**Comment by gsegares** [comment]
Duplicate of #4
