### ISSUE TITLE
Problem with some names.

### ISSUE THREAD

**Issue by FernanOrtega** [Microsoft/AISchoolTutorials#8]
Hi there,

I'm following your tutorial for JFK Files but I'm stuck in the step in which I create a custom Cognitive Skill.

You provided the following code for the function method "RunCryptonymLinker":

        [FunctionName("link-cryptonyms")]
        public static IActionResult RunCryptonymLinker([HttpTrigger(AuthorizationLevel.Function, "post", Route = null)]HttpRequest req, TraceWriter log, ExecutionContext executionContext)
        {
            string skillName = executionContext.FunctionName;

            // Get the batch of input records from the request
            var requestRecords = WebApiSkillHelpers.GetRequestRecords(req);
            if (requestRecords == null)
            {
                return new BadRequestObjectResult($"{skillName} - Invalid request record array.");
            }

            // Process each record and set the cryptonym to the output if found
            WebApiSkillResponse response = WebApiSkillHelpers.ProcessRequestRecords(skillName, requestRecords,
                (inRecord, outRecord) => {
                    string word = inRecord.Data["word"] as string;
                    if (word.All(Char.IsUpper) && cryptonymLinker.Cryptonyms.TryGetValue(word, out string description))
                    {
                        outRecord.Data["cryptonym"] = new { value = word, description };
                    }
                    return outRecord;
                });

            return (ActionResult)new OkObjectResult(response);
        }

But Visual Studio says that the name `cryptonnymLinker` doesn't exist in the current context and the name `description` is used but unnassigned.

I'm very new in C# (I come from Java world) and I'm not sure how to solve it without breaking other components that I still don't understand. Following exactly your steps ends with no way to build the solution. I recommend to update the tutorial or the provided source code.

Regards.

**Comment by FernanOrtega** [comment]
I just found another resource in your repository that solves the problem:

[(https://github.com/Microsoft/AISchoolTutorials/blob/master/jfkfiles/resources/advanced-pipeline/JfkWebAPISkills.cs)]

It simple adds the following line:
`CryptonymLinker cryptonymLinker = new CryptonymLinker(executionContext.FunctionAppDirectory);`

This should be fixed both in the Readme.md and in the Tutorial web page ([https://aischool.microsoft.com/en-us/services/learning-paths/the-jfk-files/jfk-files-lab/create-a-custom-cognitive-skill])

Regards.

**Comment by gsegares** [comment]
Hi! thanks for your feedback, the documentation was adjusted and regarding the **description** variable it is assigned in this line (output variable): cryptonymLinker.Cryptonyms.TryGetValue(word, out string description)

**Comment by gsegares** [comment]
You can follow this lab in the new Github repo https://github.com/Microsoft/ailab
